version: "3.8"

services:
  # === FRONTEND (Cara al público) ===
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/frontend:latest
    restart: always
    ports:
      - "80:3000" # Puerto 80 para que entren los usuarios
    env_file: .env

  # === CORE SERVICES ===
  auth-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/auth-service:latest
    restart: always
    ports:
      - "4004:4004"
    env_file: .env

  users-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/users-service:latest
    restart: always
    ports:
      - "4007:4007"
    env_file: .env

  profile-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/profile-service:latest
    restart: always
    ports:
      - "4005:4005"
    env_file: .env
