version: "3.8"

services:
  posts-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/posts-service:latest
    restart: always
    ports:
      - "4002:4002"
    env_file: .env

  requests-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/requests-service:latest
    restart: always
    ports:
      - "4003:4003"
    env_file: .env

  notification-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/notification-service:latest
    restart: always
    ports:
      - "4001:4001"
    env_file: .env

  ratings-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ratings-service:latest
    restart: always
    ports:
      - "4006:4006"
    env_file: .env

  messages-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/messages-service:latest
    restart: always
    ports:
      - "4008:4008"
    env_file: .env

  conversations-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/conversations-service:latest
    restart: always
    ports:
      - "4009:4009"
    env_file: .env

  chat-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/chat-service:latest
    restart: always
    ports:
      - "4010:4010"
    env_file: .env
