services:
  # INFRAESTRUCTURA
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - microservices-net

  # KAFKA STACK
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net

  # MICROSERVICIOS
  auth-service:
    image: ghcr.io/jettro12/auth-service:latest
    container_name: auth-service
    env_file:
      - ../.env
    environment:
      PORT: 4004
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672
    networks:
      - microservices-net

  users-service:
    image: ghcr.io/jettro12/users-service:latest
    container_name: users-service
    env_file:
      - ../.env
    environment:
      PORT: 4007
    networks:
      - microservices-net

  posts-service:
    image: ghcr.io/jettro12/posts-service:latest
    container_name: posts-service
    env_file:
      - ../.env
    environment:
      PORT: 4002
      KAFKA_BROKER: kafka:9092
    networks:
      - microservices-net

  profile-service:
    image: ghcr.io/jettro12/profile-service:latest
    container_name: profile-service
    env_file:
      - ../.env
    environment:
      PORT: 4005
    networks:
      - microservices-net

  # API GATEWAY
  api-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-net

  # FRONTEND
  frontend:
    image: ghcr.io/jettro12/frontend:latest
    container_name: frontend
    expose:
      - "3000"
    env_file:
      - ../.env
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://app-alb-1381202935.us-east-1.elb.amazonaws.com"
      NEXTAUTH_URL: "http://app-alb-1381202935.us-east-1.elb.amazonaws.com"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
